version: "3"

services:
  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./:/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: .
    volumes:
      - ./:/app
    working_dir: /app